=== 2ovob4ehko/zvit/blank/E04T00I.xsd
<?xml version="1.0" encoding="windows-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="DECLAR" type="DeclareType"/>
	<xs:complexType name="DeclareType">
		<xs:sequence>
			<xs:element name="DECLARHEAD" type="DeclareHeadType"/>
			<xs:element name="DECLARBODY" type="DeclarBodyType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DeclareHeadType">
		<xs:sequence>
			<xs:element name="VER">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="C_DOC">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="C_PFU">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:totalDigits value="5"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="C_REG">
			        <xs:simpleType>
				        <xs:restriction base="xs:integer">
					        <xs:minInclusive value="1"/>
					        <xs:maxInclusive value="99"/>
				        </xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="C_RAJ">
			        <xs:simpleType>
				        <xs:restriction base="xs:integer">
					        <xs:minInclusive value="1"/>
					        <xs:maxInclusive value="99"/>
				        </xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SOFTWARE" type="xs:string"/>
			<xs:element name="TIN">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PERIOD_MONTH">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PERIOD_YEAR">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DATA_FILL">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="8"/>
						<xs:minInclusive value="0"/>
						<xs:pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DeclarBodyType">
		<xs:sequence>
			<xs:element name="PAGE" type="PageType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PageType">
		<xs:sequence>
			<xs:element name="HEADER" type="HeaderType"/>
			<xs:element name="TABLE" type="TableType"/>
			<xs:element name="FOOTER" type="FooterType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HeaderType">
		<xs:sequence>
			<xs:element name="FIRM_EDRPOU">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FIRM_NAME">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="LIKV_EDRPOU" nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FIRM_ADR" type="xs:string" nillable="true"/>
			<xs:element name="FIRM_PHON" type="xs:string" nillable="true"/>
			<xs:element name="DPACD_ST">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:totalDigits value="4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FORM_TYPE">
				<xs:annotation>
					<xs:documentation>Тільки для звітів з таблицями 5-9, можливі значення 1,3 та 5</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TableType">
		<xs:sequence>
			<xs:element name="N1_0" type="xs:integer"/>
			<xs:element name="N2_0" type="xs:integer"/>
			<xs:element name="N3_0" type="xs:integer"/>
			<xs:element name="N4_0" type="xs:integer"/>
			<xs:element name="N5_0" type="xs:integer"/>
			<xs:element name="N5_1" type="xs:integer"/>
			<xs:element name="N6_0" type="xs:integer"/>
			<xs:element name="N6_1" type="xs:integer"/>
			<xs:element name="N7_0" type="xs:integer"/>
			<xs:element name="N7_1" type="xs:integer"/>
			<xs:element name="N8_0" type="xs:integer"/>
			<xs:element name="N8_1" type="xs:integer"/>
			<xs:element name="N9_0" type="xs:integer"/>
			<xs:element name="N9_1" type="xs:integer"/>
			<xs:element name="N10_0" type="xs:integer"/>
			<xs:element name="N10_1" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FooterType">
		<xs:sequence>
			<xs:element name="BOSS_NUMIDENT">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FIRM_BOSS">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="BUH_NUMIDENT" nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FIRM_BUH" nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== 2ovob4ehko/zvit/xml/23013314711918E04T00I100000000110820152301.xml
<?xml version="1.0" encoding="windows-1251"?>
<DECLAR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E04T00I.xsd">
	<DECLARHEAD>
		<VER>I</VER>
		<C_DOC>E04</C_DOC>
		<C_PFU>23273</C_PFU>
		<C_REG>23</C_REG>
		<C_RAJ>1</C_RAJ>
		<SOFTWARE>EDZV 1.17.0</SOFTWARE>
		<TIN>3314711918</TIN>
		<PERIOD_MONTH>8</PERIOD_MONTH>
		<PERIOD_YEAR>2015</PERIOD_YEAR>
		<DATA_FILL>01082015</DATA_FILL>
	</DECLARHEAD>
	<DECLARBODY>
		<PAGE>
			<HEADER>
				<FIRM_EDRPOU>3314711918</FIRM_EDRPOU>
				<FIRM_NAME>ФОП Головченко Максим Миколайович</FIRM_NAME>
				<LIKV_EDRPOU xsi:nil="true"></LIKV_EDRPOU>
				<FIRM_ADR>м. Черкаси вул. Гагаріна 75 кв 85</FIRM_ADR>
				<FIRM_PHON>764862</FIRM_PHON>
				<DPACD_ST>2301</DPACD_ST>
				<FORM_TYPE>1</FORM_TYPE>
			</HEADER>
			<TABLE>
				<N1_0>5</N1_0>
				<N2_0>0</N2_0>
				<N3_0>0</N3_0>
				<N4_0>0</N4_0>
				<N5_0>0</N5_0>
				<N5_1>0</N5_1>
				<N6_0>1</N6_0>
				<N6_1>2</N6_1>
				<N7_0>0</N7_0>
				<N7_1>0</N7_1>
				<N8_0>0</N8_0>
				<N8_1>0</N8_1>
				<N9_0>0</N9_0>
				<N9_1>0</N9_1>
				<N10_0>6</N10_0>
				<N10_1>2</N10_1>
			</TABLE>
			<FOOTER>
				<BOSS_NUMIDENT>3314711918</BOSS_NUMIDENT>
				<FIRM_BOSS>ФОП Головченко Максим Миколайович</FIRM_BOSS>
				<BUH_NUMIDENT xsi:nil="true"></BUH_NUMIDENT>
				<FIRM_BUH xsi:nil="true"></FIRM_BUH>
			</FOOTER>
		</PAGE>
	</DECLARBODY>
</DECLAR>
