=== 2ovob4ehko/zvit/blank/E04T06I.xsd
<?xml version="1.0" encoding="windows-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="DECLAR" type="DeclareType"/>
	<xs:complexType name="DeclareType">
		<xs:sequence>
			<xs:element name="DECLARHEAD" type="DeclareHeadType"/>
			<xs:element name="DECLARBODY" type="DeclarBodyType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DeclareHeadType">
		<xs:sequence>
			<xs:element name="VER">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="C_DOC">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="C_PFU">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:totalDigits value="5"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="C_REG">
			        <xs:simpleType>
				        <xs:restriction base="xs:integer">
					        <xs:minInclusive value="1"/>
					        <xs:maxInclusive value="99"/>
				        </xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="C_RAJ">
			        <xs:simpleType>
				        <xs:restriction base="xs:integer">
					        <xs:minInclusive value="1"/>
					        <xs:maxInclusive value="99"/>
				        </xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SOFTWARE" type="xs:string"/>
			<xs:element name="TIN">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PERIOD_MONTH">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PERIOD_YEAR">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DATA_FILL">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="8"/>
						<xs:minInclusive value="0"/>
						<xs:pattern value="[0-3][0-9][0-1][0-9][0-2][0-9][0-9][0-9]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DeclarBodyType">
		<xs:sequence>
			<xs:element name="PAGE" type="PageType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PageType">
		<xs:sequence>
			<xs:element name="HEADER" type="HeaderType"/>
			<xs:element name="TABLE" type="TableType"/>
			<xs:element name="FOOTER" type="FooterType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HeaderType">
		<xs:sequence>
			<xs:element name="PAGE_NUM" type="xs:integer"/>
			<xs:element name="FIRM_EDRPOU">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FIRM_NAME">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="LIKV_EDRPOU" nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FORM_TYPE">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TableType">
		<xs:sequence>
			<xs:element name="ROW" type="RowType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RowType">
		<xs:sequence>
			<xs:element name="ROWNUM" type="xs:integer"/>
			<xs:element name="UKR_GROMAD">
				<xs:annotation>
					<xs:documentation>1-так, 0-ні</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="1"/>
						<xs:totalDigits value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ST">
				<xs:annotation>
					<xs:documentation>1-М, 0-Ж</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="1"/>
						<xs:totalDigits value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="NUMIDENT">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ZO">
				<xs:annotation>
					<xs:documentation>Код катего-рії ЗО</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PAY_TP" nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="2"/>
						<xs:maxInclusive value="13"/>
						<xs:minInclusive value="01"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PAY_MNTH">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="2"/>
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PAY_YEAR">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="LN">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="NM">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FTN" nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="KD_NP" nillable="true">
				<xs:annotation>
					<xs:documentation>Кількість днів тимчасової непрацездатності</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="3"/>
						<xs:minInclusive value="-31"/>
						<xs:maxInclusive value="31"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="KD_NZP" nillable="true">
				<xs:annotation>
					<xs:documentation>Кількість днів без зберезення заробітної плати</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="3"/>
						<xs:minInclusive value="-31"/>
						<xs:maxInclusive value="31"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="KD_PTV" nillable="true">
				<xs:annotation>
					<xs:documentation>Кількість календарних днів перебування у трудових/ЦП  відносинах (обовязкове якщо звітний місяць)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="3"/>
						<xs:minInclusive value="-31"/>
						<xs:maxInclusive value="31"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="KD_VP" nillable="true">
				<xs:annotation>
					<xs:documentation>Кількість календарних по вагітності та пологам</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="3"/>
						<xs:minInclusive value="-31"/>
						<xs:maxInclusive value="31"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SUM_TOTAL">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SUM_MAX">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SUM_DIFF">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SUM_INS">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SUM_NARAH">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="OTK">
				<xs:annotation>
					<xs:documentation>1-так, 0-ні</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="1"/>
						<xs:enumeration value="0"/>
						<xs:enumeration value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="EXP">
				<xs:annotation>
					<xs:documentation>Ознака наявності спец-стажу (1-так, 0-ні)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="1"/>
						<xs:enumeration value="0"/>
						<xs:enumeration value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="NRC">
				<xs:annotation>
					<xs:documentation>Ознака неповного робочого часу (1-так, 0-ні)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="1"/>
						<xs:enumeration value="0"/>
						<xs:enumeration value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="NRM">
				<xs:annotation>
					<xs:documentation>Ознака нового робочого місця (1-так, 0-ні)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:totalDigits value="1"/>
						<xs:enumeration value="0"/>
						<xs:enumeration value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FooterType">
		<xs:sequence>
			<xs:element name="PAGE_SUM_TOTAL">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PAGE_SUM_MAX">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PAGE_SUM_DIFF">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PAGE_SUM_INS">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PAGE_SUM_NARAH">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ROWS">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="10"/>
						<xs:totalDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="BOSS_NUMIDENT">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FIRM_BOSS">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="BUH_NUMIDENT" nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FIRM_BUH" nillable="true">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== 2ovob4ehko/zvit/xml/23013314711918E04T06I100000000110820152301.xml
<?xml version="1.0" encoding="windows-1251"?>
<DECLAR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E04T06I.xsd">
	<DECLARHEAD>
		<VER>I</VER>
		<C_DOC>E04</C_DOC>
		<C_PFU>23273</C_PFU>
		<C_REG>23</C_REG>
		<C_RAJ>1</C_RAJ>
		<SOFTWARE>EDZV 1.17.0</SOFTWARE>
		<TIN>3314711918</TIN>
		<PERIOD_MONTH>8</PERIOD_MONTH>
		<PERIOD_YEAR>2015</PERIOD_YEAR>
		<DATA_FILL>01082015</DATA_FILL>
	</DECLARHEAD>
	<DECLARBODY>
		<PAGE>
			<HEADER>
				<PAGE_NUM>1</PAGE_NUM>
				<FIRM_EDRPOU>3314711918</FIRM_EDRPOU>
				<FIRM_NAME>ФОП Головченко Максим Миколайович</FIRM_NAME>
				<LIKV_EDRPOU xsi:nil="true"></LIKV_EDRPOU>
				<FORM_TYPE>1</FORM_TYPE>
			</HEADER>
			<TABLE>
				<ROW>
					<ROWNUM>1</ROWNUM>
					<UKR_GROMAD>1</UKR_GROMAD>
					<ST>1</ST>
					<NUMIDENT>1212121212</NUMIDENT>
					<ZO>1</ZO>
					<PAY_TP xsi:nil="true"></PAY_TP>
					<PAY_MNTH>08</PAY_MNTH>
					<PAY_YEAR>2015</PAY_YEAR>
					<LN>Головченко</LN>
					<NM>Максим</NM>
					<FTN>Миколайович</FTN>
					<KD_NP xsi:nil="true"></KD_NP>
					<KD_NZP xsi:nil="true"></KD_NZP>
					<KD_PTV>31</KD_PTV>
					<KD_VP xsi:nil="true"></KD_VP>
					<SUM_TOTAL>1218.00</SUM_TOTAL>
					<SUM_MAX>1218.00</SUM_MAX>
					<SUM_DIFF>0.00</SUM_DIFF>
					<SUM_INS>43.85</SUM_INS>
					<SUM_NARAH>43.85</SUM_NARAH>
					<OTK>1</OTK>
					<EXP>0</EXP>
					<NRC>0</NRC>
					<NRM>0</NRM>
				</ROW>
				<ROW>
					<ROWNUM>2</ROWNUM>
					<UKR_GROMAD>1</UKR_GROMAD>
					<ST>0</ST>
					<NUMIDENT>1313131313</NUMIDENT>
					<ZO>1</ZO>
					<PAY_TP xsi:nil="true"></PAY_TP>
					<PAY_MNTH>08</PAY_MNTH>
					<PAY_YEAR>2015</PAY_YEAR>
					<LN>Головченко</LN>
					<NM>Марина</NM>
					<FTN>Миколаївна</FTN>
					<KD_NP xsi:nil="true"></KD_NP>
					<KD_NZP xsi:nil="true"></KD_NZP>
					<KD_PTV>31</KD_PTV>
					<KD_VP xsi:nil="true"></KD_VP>
					<SUM_TOTAL>1218.00</SUM_TOTAL>
					<SUM_MAX>1218.00</SUM_MAX>
					<SUM_DIFF>0.00</SUM_DIFF>
					<SUM_INS>43.85</SUM_INS>
					<SUM_NARAH>43.85</SUM_NARAH>
					<OTK>1</OTK>
					<EXP>0</EXP>
					<NRC>0</NRC>
					<NRM>0</NRM>
				</ROW>
			</TABLE>
			<FOOTER>
				<PAGE_SUM_TOTAL>2436.00</PAGE_SUM_TOTAL>
				<PAGE_SUM_MAX>2436.00</PAGE_SUM_MAX>
				<PAGE_SUM_DIFF>0.00</PAGE_SUM_DIFF>
				<PAGE_SUM_INS>87.70</PAGE_SUM_INS>
				<PAGE_SUM_NARAH>87.70</PAGE_SUM_NARAH>
				<ROWS>2</ROWS>
				<BOSS_NUMIDENT>3314711918</BOSS_NUMIDENT>
				<FIRM_BOSS>ФОП Головченко Максим Миколайович</FIRM_BOSS>
				<BUH_NUMIDENT xsi:nil="true"></BUH_NUMIDENT>
				<FIRM_BUH xsi:nil="true"></FIRM_BUH>
			</FOOTER>
		</PAGE>
	</DECLARBODY>
</DECLAR>
